version: '3.8'

services:
  api:
    build: ..
    container_name: social_ai_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ../.env  # Все переменные здесь
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  dashboard:
    build: ..
    container_name: social_ai_dashboard
    command: streamlit run app/frontend/dashboard.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    env_file:
      - ../.env
    depends_on:
      - api
    restart: unless-stopped
