"""update role

Revision ID: 0003
Revises: 0002
Create Date: 2025-09-14 14:05:40.638985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True), schema='social_manager')
    op.add_column('users', sa.Column('role_id', sa.Integer(), nullable=True), schema='social_manager')
    op.drop_constraint(op.f('users_email_key'), 'users', schema='social_manager', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', schema='social_manager', type_='unique')
    op.create_index(op.f('ix_social_manager_users_email'), 'users', ['email'], unique=True, schema='social_manager')
    op.create_index(op.f('ix_social_manager_users_username'), 'users', ['username'], unique=True, schema='social_manager')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], source_schema='social_manager', referent_schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', schema='social_manager', type_='foreignkey')
    op.drop_index(op.f('ix_social_manager_users_username'), table_name='users', schema='social_manager')
    op.drop_index(op.f('ix_social_manager_users_email'), table_name='users', schema='social_manager')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], schema='social_manager', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], schema='social_manager', postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'role_id', schema='social_manager')
    op.drop_column('users', 'is_superuser', schema='social_manager')
    # ### end Alembic commands ###
