"""Rebuild models

Revision ID: 0007
Revises: 0006
Create Date: 2025-10-07 15:31:46.065989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0007'
down_revision: Union[str, Sequence[str], None] = '0006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_scenarios',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=False),
                    sa.Column('trigger_conditions', sa.JSON(), nullable=True),
                    sa.Column('ai_prompt', sa.Text(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('cooldown_minutes', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='social_manager'
                    )
    op.create_table('platforms',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('platform_type', sa.String(length=20), nullable=False),
                    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
                    sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
                    sa.Column('rate_limit_reset_at', sa.DateTime(), nullable=True),
                    sa.Column('last_sync', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name'),
                    schema='social_manager'
                    )
    op.create_table('sources',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('platform_id', sa.Integer(), nullable=False),
                    sa.Column('source_type', sa.String(length=50), nullable=False),
                    sa.Column('external_id', sa.String(length=100), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('params', sa.JSON(), server_default='{}', nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('last_checked', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['platform_id'], ['social_manager.platforms.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('platform_id', 'external_id', name='uq_source_platform_external'),
                    schema='social_manager'
                    )
    op.create_index('idx_sources_external_id', 'sources', ['external_id'], unique=False, schema='social_manager')
    op.create_index('idx_sources_last_checked', 'sources', ['last_checked'], unique=False, schema='social_manager')
    op.create_index('idx_sources_platform_id', 'sources', ['platform_id'], unique=False, schema='social_manager')
    op.create_table('ai_analytics',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('source_id', sa.Integer(), nullable=False),
                    sa.Column('analysis_date', sa.Date(), nullable=False),
                    sa.Column('period_type', sa.String(length=20), nullable=True),
                    sa.Column('summary_data', sa.JSON(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['source_id'], ['social_manager.sources.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('source_id', 'analysis_date', 'period_type',
                                        name='uq_analytics_source_date_period'),
                    schema='social_manager'
                    )
    op.create_index('idx_ai_analytics_date', 'ai_analytics', ['analysis_date'], unique=False, schema='social_manager')
    op.create_index('idx_ai_analytics_source', 'ai_analytics', ['source_id'], unique=False, schema='social_manager')
    op.create_table('source_user_relationships',
                    sa.Column('source_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=True),
                    sa.Column('params', sa.JSON(), server_default='{}', nullable=True),
                    sa.ForeignKeyConstraint(['source_id'], ['social_manager.sources.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['social_manager.sources.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('source_id', 'user_id'),
                    schema='social_manager'
                    )

    op.execute('DROP TABLE IF EXISTS social_manager.comments CASCADE')
    op.execute('DROP TABLE IF EXISTS social_manager.posts CASCADE')
    op.execute('DROP TABLE IF EXISTS social_manager.statistics CASCADE')
    op.execute('DROP TABLE IF EXISTS social_manager.ai_analysis_results CASCADE')
    op.execute('DROP TABLE IF EXISTS social_manager.social_groups CASCADE')
    op.execute('DROP TABLE IF EXISTS social_manager.social_accounts CASCADE')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.create_unique_constraint(op.f('roles_codename_key'), 'roles', ['codename'], schema='social_manager', postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.add_column('role_permission', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True), schema='social_manager')
    op.drop_constraint(None, 'role_permission', schema='social_manager', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(op.f('role_permission_permission_id_fkey'), 'role_permission', 'permissions', ['permission_id'], ['id'], source_schema='social_manager', referent_schema='social_manager', ondelete='CASCADE')
    op.create_foreign_key(op.f('role_permission_role_id_fkey'), 'role_permission', 'roles', ['role_id'], ['id'], source_schema='social_manager', referent_schema='social_manager', ondelete='CASCADE')
    op.drop_constraint('uq_permission_model_type', 'permissions', schema='social_manager', type_='unique')
    op.create_unique_constraint(op.f('permissions_new_codename_action_type_model_type_id_key'), 'permissions', ['codename', 'action_type', 'model_type_id'], schema='social_manager', postgresql_nulls_not_distinct=False)
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True,
               schema='social_manager')
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True,
               schema='social_manager')
    op.alter_column('permissions', 'model_type_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='social_manager')
    op.add_column('notifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='social_manager')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], source_schema='social_manager', referent_schema='social_manager')
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.add_column('model_types', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='social_manager')
    op.add_column('model_types', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False), schema='social_manager')
    op.create_table('social_accounts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('social_manager.social_accounts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('platform_user_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('access_token', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('refresh_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('profile_data', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['social_manager.users.id'], name='social_accounts_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='social_accounts_pkey'),
    schema='social_manager',
    postgresql_ignore_search_path=False
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform_comment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('author_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('author_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_label', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('comment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['social_manager.posts.id'], name=op.f('comments_post_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('comments_pkey')),
    schema='social_manager'
    )
    op.create_table('statistics',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['social_manager.social_groups.id'], name=op.f('statistics_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('statistics_pkey')),
    schema='social_manager'
    )
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform_post_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('likes_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('comments_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('reposts_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('views_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('post_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['social_manager.social_groups.id'], name=op.f('posts_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey')),
    schema='social_manager'
    )
    op.create_table('social_groups',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('social_manager.social_groups_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('social_account_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('platform_group_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('screen_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('members_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_tracking', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('settings', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_manager.social_accounts.id'], name='social_groups_social_account_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='social_groups_pkey'),
    schema='social_manager',
    postgresql_ignore_search_path=False
    )
    op.create_table('ai_analysis_results',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('analysis_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('results', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['social_manager.social_groups.id'], name=op.f('ai_analysis_results_group_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ai_analysis_results_pkey')),
    schema='social_manager'
    )
    op.drop_table('source_user_relationships', schema='social_manager')
    op.drop_index('idx_ai_analytics_source', table_name='ai_analytics', schema='social_manager')
    op.drop_index('idx_ai_analytics_date', table_name='ai_analytics', schema='social_manager')
    op.drop_table('ai_analytics', schema='social_manager')
    op.drop_index('idx_sources_platform_id', table_name='sources', schema='social_manager')
    op.drop_index('idx_sources_last_checked', table_name='sources', schema='social_manager')
    op.drop_index('idx_sources_external_id', table_name='sources', schema='social_manager')
    op.drop_table('sources', schema='social_manager')
    op.drop_table('platforms', schema='social_manager')
    op.drop_table('bot_scenarios', schema='social_manager')
    # ### end Alembic commands ###
