"""update enums

Revision ID: 0008
Revises: 0007
Create Date: 2025-10-07 18:39:26.533261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008'
down_revision: Union[str, Sequence[str], None] = '0007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Сначала создаем все ENUM типы
    analysisperiod_type = sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='analysisperiod_type',
                                 schema='social_manager')
    notification_type = sa.Enum('REPORT_READY', 'MOOD_CHANGE', 'TREND_ALERT', 'TOPIC_RESUMED', 'API_ERROR',
                               'CONNECTION_ERROR', 'SOURCE_INACTIVE', 'RATE_LIMIT_WARNING', 'BOT_COMMENT',
                               'BOT_SKIPPED', 'SYSTEM_BACKUP', 'SYSTEM_UPDATE', 'SUBSCRIBED_ACTIVITY',
                               'KEYWORD_MENTION', name='notification_type', schema='social_manager')
    platform_type = sa.Enum('SOCIAL', 'MESSENGER', name='platform_type', schema='social_manager')
    source_type = sa.Enum('USER', 'GROUP', 'CHANNEL', 'CHAT', 'PAGE', 'PUBLIC', 'EVENT', 'MARKET', 'ALBUM', 'SUPERGROUP',
                         'BOT', 'BROADCAST', name='source_type', schema='social_manager')

    # Создаем ENUM типы
    analysisperiod_type.create(op.get_bind(), checkfirst=True)
    notification_type.create(op.get_bind(), checkfirst=True)
    platform_type.create(op.get_bind(), checkfirst=True)
    source_type.create(op.get_bind(), checkfirst=True)

    # 2. Теперь изменяем колонки с явным преобразованием lowercase → UPPERCASE
    op.alter_column('ai_analytics', 'period_type',
                    existing_type=sa.VARCHAR(length=20),
                    type_=analysisperiod_type,
                    postgresql_using="UPPER(period_type)::social_manager.analysisperiod_type",
                    nullable=False,
                    schema='social_manager')

    op.alter_column('notifications', 'notification_type',
                    existing_type=sa.VARCHAR(length=50),
                    type_=notification_type,
                    postgresql_using="UPPER(notification_type)::social_manager.notification_type",
                    nullable=False,
                    schema='social_manager')

    op.alter_column('platforms', 'platform_type',
                    existing_type=sa.VARCHAR(length=20),
                    type_=platform_type,
                    postgresql_using="UPPER(platform_type)::social_manager.platform_type",
                    existing_nullable=False,
                    schema='social_manager')

    op.alter_column('sources', 'source_type',
                    existing_type=sa.VARCHAR(length=50),
                    type_=source_type,
                    postgresql_using="UPPER(source_type)::social_manager.source_type",
                    existing_nullable=False,
                    schema='social_manager')

    # 3. Остальные операции (без изменений)
    op.drop_constraint(op.f('ai_analytics_source_id_fkey'), 'ai_analytics', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analytics', 'sources', ['source_id'], ['id'], source_schema='social_manager',
                          referent_schema='social_manager', ondelete='CASCADE')

    op.alter_column('model_types', 'created_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False,
                    schema='social_manager')
    op.alter_column('model_types', 'updated_at',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.DateTime(timezone=True),
                    existing_nullable=False,
                    schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.drop_constraint(None, 'sources', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(op.f('sources_platform_id_fkey'), 'sources', 'platforms', ['platform_id'], ['id'], source_schema='social_manager', referent_schema='social_manager')
    op.alter_column('sources', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('sources', 'source_type',
               existing_type=sa.Enum('USER', 'GROUP', 'CHANNEL', 'CHAT', 'PAGE', 'PUBLIC', 'EVENT', 'MARKET', 'ALBUM', 'SUPERGROUP', 'BOT', 'BROADCAST', name='sourcetype', schema='social_manager', inherit_schema=True),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('source_user_relationships', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('source_user_relationships', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True,
               schema='social_manager')
    op.add_column('roles', sa.Column('codename', postgresql.ENUM('VIEWER', 'AI_BOT', 'MANAGER', 'ANALYST', 'MODERATOR', 'ADMIN', 'SUPERUSER', name='user_role_type', schema='social_manager'), autoincrement=False, nullable=False), schema='social_manager')
    op.create_unique_constraint(op.f('roles_codename_key'), 'roles', ['codename'], schema='social_manager', postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.drop_column('roles', 'user_role_type', schema='social_manager')
    op.add_column('role_permission', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True), schema='social_manager')
    op.drop_constraint(None, 'role_permission', schema='social_manager', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(op.f('role_permission_permission_id_fkey'), 'role_permission', 'permissions', ['permission_id'], ['id'], source_schema='social_manager', referent_schema='social_manager', ondelete='CASCADE')
    op.create_foreign_key(op.f('role_permission_role_id_fkey'), 'role_permission', 'roles', ['role_id'], ['id'], source_schema='social_manager', referent_schema='social_manager', ondelete='CASCADE')
    op.alter_column('platforms', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('platforms', 'platform_type',
               existing_type=sa.Enum('SOCIAL', 'MESSENGER', name='platformtype', schema='social_manager', inherit_schema=True),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               schema='social_manager')
    op.drop_constraint('uq_permission_model_type', 'permissions', schema='social_manager', type_='unique')
    op.create_unique_constraint(op.f('permissions_new_codename_action_type_model_type_id_key'), 'permissions', ['codename', 'action_type', 'model_type_id'], schema='social_manager', postgresql_nulls_not_distinct=False)
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True,
               schema='social_manager')
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True,
               schema='social_manager')
    op.alter_column('permissions', 'model_type_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='social_manager')
    op.add_column('notifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='social_manager')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], source_schema='social_manager', referent_schema='social_manager')
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('notifications', 'notification_type',
               existing_type=sa.Enum('REPORT_READY', 'MOOD_CHANGE', 'TREND_ALERT', 'TOPIC_RESUMED', 'API_ERROR', 'CONNECTION_ERROR', 'SOURCE_INACTIVE', 'RATE_LIMIT_WARNING', 'BOT_COMMENT', 'BOT_SKIPPED', 'SYSTEM_BACKUP', 'SYSTEM_UPDATE', 'SUBSCRIBED_ACTIVITY', 'KEYWORD_MENTION', name='notificationtype', schema='social_manager', inherit_schema=True),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               schema='social_manager')
    op.alter_column('model_types', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('model_types', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.drop_constraint(None, 'ai_analytics', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(op.f('ai_analytics_source_id_fkey'), 'ai_analytics', 'sources', ['source_id'], ['id'], source_schema='social_manager', referent_schema='social_manager')
    op.alter_column('ai_analytics', 'period_type',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'CUSTOM', name='analysisperiodtype', schema='social_manager', inherit_schema=True),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               schema='social_manager')
    # ### end Alembic commands ###
