"""update defaults

Revision ID: 0009
Revises: 0008
Create Date: 2025-10-08 20:37:08.773146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0009'
down_revision: Union[str, Sequence[str], None] = '0008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analytics', 'analysis_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               nullable=True,
               schema='social_manager')
    op.alter_column('ai_analytics', 'summary_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='social_manager')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', schema='social_manager', type_='foreignkey')
    op.drop_column('notifications', 'user_id', schema='social_manager')
    op.alter_column('permissions', 'model_type_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               schema='social_manager')
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False,
               schema='social_manager')
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               nullable=False,
               schema='social_manager')
    op.drop_constraint(op.f('permissions_new_codename_action_type_model_type_id_key'), 'permissions', schema='social_manager', type_='unique')
    op.create_unique_constraint('uq_permission_model_type', 'permissions', ['codename', 'model_type_id'], schema='social_manager')
    op.add_column(
        'platforms',
        sa.Column('base_url', sa.String(length=255), nullable=False, server_default=''),
        schema='social_manager'
    )
    op.add_column(
        'platforms',
        sa.Column('params', sa.JSON(), nullable=False, server_default=sa.text("'{}'::json")),
        schema='social_manager'
    )
    op.alter_column(
        'platforms',
        'base_url',
        server_default=None,
        existing_type=sa.String(length=255),
        schema='social_manager'
    )
    op.alter_column(
        'platforms',
        'params',
        server_default=None,
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        schema='social_manager'
    )
    op.drop_column('platforms', 'last_sync', schema='social_manager')
    op.drop_constraint(op.f('role_permission_permission_id_fkey'), 'role_permission', schema='social_manager', type_='foreignkey')
    op.drop_constraint(op.f('role_permission_role_id_fkey'), 'role_permission', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(None, 'role_permission', 'roles', ['role_id'], ['id'], source_schema='social_manager', referent_schema='social_manager')
    op.create_foreign_key(None, 'role_permission', 'permissions', ['permission_id'], ['id'], source_schema='social_manager', referent_schema='social_manager')
    op.drop_column('role_permission', 'created_at', schema='social_manager')
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='social_manager')
    op.drop_constraint(op.f('roles_codename_key'), 'roles', schema='social_manager', type_='unique')
    op.alter_column('source_user_relationships', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('source_user_relationships', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=True,
               schema='social_manager')
    op.execute(
        sa.text(
            "UPDATE social_manager.sources SET name = COALESCE(name, external_id, 'Unnamed source')"
        )
    )
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False,
               schema='social_manager')
    op.alter_column('sources', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.drop_constraint(op.f('sources_platform_id_fkey'), 'sources', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(None, 'sources', 'platforms', ['platform_id'], ['id'], source_schema='social_manager', referent_schema='social_manager', ondelete='CASCADE')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.drop_constraint(None, 'sources', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(op.f('sources_platform_id_fkey'), 'sources', 'platforms', ['platform_id'], ['id'], source_schema='social_manager', referent_schema='social_manager')
    op.alter_column('sources', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('sources', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True,
               schema='social_manager')
    op.alter_column('source_user_relationships', 'params',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('source_user_relationships', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True,
               schema='social_manager')
    op.create_unique_constraint(op.f('roles_codename_key'), 'roles', ['codename'], schema='social_manager', postgresql_nulls_not_distinct=False)
    op.alter_column('roles', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('roles', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.add_column('role_permission', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True), schema='social_manager')
    op.drop_constraint(None, 'role_permission', schema='social_manager', type_='foreignkey')
    op.drop_constraint(None, 'role_permission', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(op.f('role_permission_role_id_fkey'), 'role_permission', 'roles', ['role_id'], ['id'], source_schema='social_manager', referent_schema='social_manager', ondelete='CASCADE')
    op.create_foreign_key(op.f('role_permission_permission_id_fkey'), 'role_permission', 'permissions', ['permission_id'], ['id'], source_schema='social_manager', referent_schema='social_manager', ondelete='CASCADE')
    op.add_column('platforms', sa.Column('last_sync', postgresql.TIMESTAMP(), autoincrement=False, nullable=True), schema='social_manager')
    op.drop_column('platforms', 'params', schema='social_manager')
    op.drop_column('platforms', 'base_url', schema='social_manager')
    op.drop_constraint('uq_permission_model_type', 'permissions', schema='social_manager', type_='unique')
    op.create_unique_constraint(op.f('permissions_new_codename_action_type_model_type_id_key'), 'permissions', ['codename', 'action_type', 'model_type_id'], schema='social_manager', postgresql_nulls_not_distinct=False)
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True,
               schema='social_manager')
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True,
               schema='social_manager')
    op.alter_column('permissions', 'model_type_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               schema='social_manager')
    op.add_column('notifications', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True), schema='social_manager')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'], source_schema='social_manager', referent_schema='social_manager')
    op.alter_column('notifications', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('notifications', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('ai_analytics', 'summary_data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('ai_analytics', 'analysis_date',
               existing_type=sa.DATE(),
               server_default=None,
               nullable=False,
               schema='social_manager')
    # ### end Alembic commands ###
