"""update source user relationships

Revision ID: 0012
Revises: 0011
Create Date: 2025-10-09 17:22:37.733872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: Union[str, Sequence[str], None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('ai_analytics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('model_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('model_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.drop_column('source_user_relationships', 'params', schema='social_manager')
    op.drop_column('source_user_relationships', 'is_active', schema='social_manager')
    op.add_column('sources', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='social_manager')
    op.add_column('sources', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='social_manager')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False,
               schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.drop_column('sources', 'updated_at', schema='social_manager')
    op.drop_column('sources', 'created_at', schema='social_manager')
    op.add_column('source_user_relationships', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True), schema='social_manager')
    op.add_column('source_user_relationships', sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='social_manager')
    op.alter_column('roles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('roles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('permissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('notifications', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('model_types', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('model_types', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('ai_analytics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('ai_analytics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    # ### end Alembic commands ###
