"""Add analysis_type to ai_analytics

Revision ID: 0020
Revises: 0012
Create Date: 2025-10-10 19:19:55.341960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0020'
down_revision: Union[str, Sequence[str], None] = '0012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create analysistype enum
    op.execute("""
        CREATE TYPE social_manager.analysis_type AS ENUM ('sentiment', 'topics', 'activity', 'keywords', 'engagement')
    """)
    
    op.add_column('ai_analytics', sa.Column('analysis_type', sa.Enum('sentiment', 'topics', 'activity', 'keywords', 'engagement', name='analysis_type', schema='social_manager', inherit_schema=True), nullable=True), schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_analytics', 'analysis_type', schema='social_manager')
    
    # Drop analysistype enum
    op.execute("DROP TYPE IF EXISTS social_manager.analysis_type")
    # ### end Alembic commands ###
