"""update types

Revision ID: 0022
Revises: 0021
Create Date: 2025-10-12 04:47:24.071163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0022'
down_revision: Union[str, Sequence[str], None] = '0021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_analytics', 'response_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='social_manager')
    op.add_column('bot_scenarios', sa.Column('scope', sa.JSON(), nullable=True), schema='social_manager')
    op.add_column('bot_scenarios', sa.Column('action_type', sa.Enum('COMMENT', 'REPLY', 'DIRECT_MESSAGE', 'POST', 'REACTION', 'MODERATION', 'NOTIFICATION', name='bot_action_type', schema='social_manager', inherit_schema=True), nullable=True), schema='social_manager')
    op.alter_column('bot_scenarios', 'content_types',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True,
               schema='social_manager')
    op.drop_column('bot_scenarios', 'trigger_conditions', schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_scenarios', sa.Column('trigger_conditions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True), schema='social_manager')
    op.alter_column('bot_scenarios', 'content_types',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='social_manager')
    op.drop_column('bot_scenarios', 'action_type', schema='social_manager')
    op.drop_column('bot_scenarios', 'scope', schema='social_manager')
    op.alter_column('ai_analytics', 'response_payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='social_manager')
    # ### end Alembic commands ###
