"""rename cooldown_minutes to collection_interval_hours

Revision ID: 0026
Revises: 0025
Create Date: 2025-10-15 11:37:00.603871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0026'
down_revision: Union[str, Sequence[str], None] = '0025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_scenarios', sa.Column('collection_interval_hours', sa.Integer(), nullable=True), schema='social_manager')
    op.alter_column('bot_scenarios', 'content_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'analysis_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.drop_index(op.f('idx_bot_scenarios_llm_mapping'), table_name='bot_scenarios', schema='social_manager', postgresql_using='gin')
    op.drop_column('bot_scenarios', 'cooldown_minutes', schema='social_manager')
    op.alter_column('llm_providers', 'capabilities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_providers', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('llm_providers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='social_manager')
    op.drop_index(op.f('idx_llm_providers_active'), table_name='llm_providers', schema='social_manager')
    op.drop_index(op.f('idx_llm_providers_type'), table_name='llm_providers', schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_llm_providers_type'), 'llm_providers', ['provider_type'], unique=False, schema='social_manager')
    op.create_index(op.f('idx_llm_providers_active'), 'llm_providers', ['is_active'], unique=False, schema='social_manager')
    op.alter_column('llm_providers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('llm_providers', 'config',
               existing_type=sa.JSON(),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('llm_providers', 'capabilities',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               schema='social_manager')
    op.add_column('bot_scenarios', sa.Column('cooldown_minutes', sa.INTEGER(), autoincrement=False, nullable=True), schema='social_manager')
    op.create_index(op.f('idx_bot_scenarios_llm_mapping'), 'bot_scenarios', [sa.literal_column('(llm_mapping::jsonb)')], unique=False, schema='social_manager', postgresql_using='gin')
    op.alter_column('bot_scenarios', 'analysis_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'[]'::json"),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'content_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               schema='social_manager')
    op.drop_column('bot_scenarios', 'collection_interval_hours', schema='social_manager')
    # ### end Alembic commands ###
