"""remove llm_mapping field

Revision ID: 0028
Revises: 0027
Create Date: 2025-10-15 12:46:07.053748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0028'
down_revision: Union[str, Sequence[str], None] = '0027'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the GIN index on llm_mapping if it exists
    op.execute("""
        DROP INDEX IF EXISTS social_manager.idx_bot_scenarios_llm_mapping;
    """)
    
    # Drop llm_mapping column
    op.drop_column('bot_scenarios', 'llm_mapping', schema='social_manager')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Re-add llm_mapping column
    op.add_column(
        'bot_scenarios',
        sa.Column('llm_mapping', sa.JSON(), nullable=True),
        schema='social_manager'
    )
    
    # Re-create GIN index
    op.execute("""
        CREATE INDEX idx_bot_scenarios_llm_mapping 
        ON social_manager.bot_scenarios USING GIN ((llm_mapping::jsonb));
    """)
    
    # ### end Alembic commands ###
