"""update ai analytics model

Revision ID: 0033
Revises: 0032
Create Date: 2025-10-16 01:33:48.095233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0033'
down_revision: Union[str, Sequence[str], None] = '0032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_ai_analytics_provider'), table_name='ai_analytics', schema='social_manager')
    op.drop_constraint(op.f('fk_ai_analytics_parent'), 'ai_analytics', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(None, 'ai_analytics', 'ai_analytics', ['parent_analysis_id'], ['id'], source_schema='social_manager', referent_schema='social_manager', ondelete='SET NULL')
    op.drop_column('ai_analytics', 'estimated_cost', schema='social_manager')
    op.drop_column('ai_analytics', 'response_tokens', schema='social_manager')
    op.drop_column('ai_analytics', 'request_tokens', schema='social_manager')
    op.drop_column('ai_analytics', 'provider_type', schema='social_manager')
    op.drop_column('ai_analytics', 'media_types', schema='social_manager')
    op.alter_column('bot_scenarios', 'text_prompt',
               existing_type=sa.TEXT(),
               comment='Custom prompt for text analysis. If null, uses default.',
               existing_comment='Custom prompt for text analysis',
               existing_nullable=True,
               schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bot_scenarios', 'text_prompt',
               existing_type=sa.TEXT(),
               comment='Custom prompt for text analysis',
               existing_comment='Custom prompt for text analysis. If null, uses default.',
               existing_nullable=True,
               schema='social_manager')
    op.add_column('ai_analytics', sa.Column('media_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Types analyzed: text, image, video'), schema='social_manager')
    op.add_column('ai_analytics', sa.Column('provider_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True, comment='LLM provider: openai, deepseek, etc'), schema='social_manager')
    op.add_column('ai_analytics', sa.Column('request_tokens', sa.INTEGER(), autoincrement=False, nullable=True, comment='Input tokens used'), schema='social_manager')
    op.add_column('ai_analytics', sa.Column('response_tokens', sa.INTEGER(), autoincrement=False, nullable=True, comment='Output tokens generated'), schema='social_manager')
    op.add_column('ai_analytics', sa.Column('estimated_cost', sa.INTEGER(), autoincrement=False, nullable=True, comment='Estimated cost in USD cents'), schema='social_manager')
    op.drop_constraint(None, 'ai_analytics', schema='social_manager', type_='foreignkey')
    op.create_foreign_key(op.f('fk_ai_analytics_parent'), 'ai_analytics', 'ai_analytics', ['parent_analysis_id'], ['id'], source_schema='social_manager', referent_schema='social_manager')
    op.create_index(op.f('idx_ai_analytics_provider'), 'ai_analytics', ['provider_type'], unique=False, schema='social_manager')
    # ### end Alembic commands ###
