"""Add fields to AIAnalytics

Revision ID: 0034
Revises: 0033
Create Date: 2025-10-16 02:19:22.752210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0034'
down_revision: Union[str, Sequence[str], None] = '0033'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analytics', sa.Column('request_tokens', sa.Integer(), nullable=True), schema='social_manager')
    op.add_column('ai_analytics', sa.Column('response_tokens', sa.Integer(), nullable=True), schema='social_manager')
    op.add_column('ai_analytics', sa.Column('estimated_cost', sa.Integer(), nullable=True), schema='social_manager')
    op.add_column('ai_analytics', sa.Column('provider_type', sa.String(length=100), nullable=True), schema='social_manager')
    op.add_column('ai_analytics', sa.Column('media_types', sa.JSON(), nullable=True), schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_analytics', 'media_types', schema='social_manager')
    op.drop_column('ai_analytics', 'provider_type', schema='social_manager')
    op.drop_column('ai_analytics', 'estimated_cost', schema='social_manager')
    op.drop_column('ai_analytics', 'response_tokens', schema='social_manager')
    op.drop_column('ai_analytics', 'request_tokens', schema='social_manager')
    # ### end Alembic commands ###
