"""add date_from and date_to to source

Revision ID: 0035
Revises: 0034
Create Date: 2025-10-18 22:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0035'
down_revision: Union[str, Sequence[str], None] = '0034'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sources', 
        sa.Column('date_from', sa.DateTime(timezone=True), nullable=True, 
                  comment='Start date for data collection (inclusive)'),
        schema='social_manager'
    )
    op.add_column('sources', 
        sa.Column('date_to', sa.DateTime(timezone=True), nullable=True,
                  comment='End date for data collection (inclusive)'),
        schema='social_manager'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'date_to', schema='social_manager')
    op.drop_column('sources', 'date_from', schema='social_manager')
    # ### end Alembic commands ###
