"""add response_format_config and output_display_config to bot_scenarios

Revision ID: 0036
Revises: 0035
Create Date: 2025-10-19 20:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0036'
down_revision: Union[str, Sequence[str], None] = '0035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_scenarios', 
        sa.Column('response_format_config', sa.JSON(), nullable=True, 
                  comment='Configuration for automatic JSON schema generation'),
        schema='social_manager'
    )
    op.add_column('bot_scenarios', 
        sa.Column('output_display_config', sa.JSON(), nullable=True,
                  comment='Configuration for rich display in dashboard'),
        schema='social_manager'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_scenarios', 'output_display_config', schema='social_manager')
    op.drop_column('bot_scenarios', 'response_format_config', schema='social_manager')
    # ### end Alembic commands ###
