"""Add main topics to AIAnalytics

Revision ID: 0039
Revises: 0038
Create Date: 2025-10-25 23:08:23.645333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0039'
down_revision: Union[str, Sequence[str], None] = '0038'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_analytics', sa.Column('main_topics', sa.JSON(), nullable=True, comment='Main topics extracted from AI analysis for theme matching'), schema='social_manager')
    op.alter_column('bot_scenarios', 'content_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'analysis_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'response_format_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Configuration for automatic JSON schema generation. Controls response structure.',
               existing_comment='Configuration for automatic JSON schema generation',
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'output_display_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Configuration for rich display in dashboard (sentiment emoji, keywords, links, etc.)',
               existing_comment='Configuration for rich display in dashboard',
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'text_llm_model_id',
               existing_type=sa.INTEGER(),
               comment='Specific LLM model for text analysis',
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'image_llm_model_id',
               existing_type=sa.INTEGER(),
               comment='Specific LLM model for image analysis',
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'video_llm_model_id',
               existing_type=sa.INTEGER(),
               comment='Specific LLM model for video analysis',
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('llm_models', 'input_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_models', 'output_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_models', 'capabilities',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_models', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               type_=sa.JSON(),
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('llm_models', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('llm_models', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('llm_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='social_manager')
    op.alter_column('llm_models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'),
               schema='social_manager')
    op.drop_column('llm_models', 'context_window', schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_models', sa.Column('context_window', sa.INTEGER(), server_default=sa.text('4096'), autoincrement=False, nullable=False), schema='social_manager')
    op.alter_column('llm_models', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='social_manager')
    op.alter_column('llm_models', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'),
               schema='social_manager')
    op.alter_column('llm_models', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('llm_models', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('llm_models', 'config',
               existing_type=sa.JSON(),
               server_default=sa.text("'{}'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('llm_models', 'capabilities',
               existing_type=sa.JSON(),
               server_default=sa.text("'[]'::jsonb"),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_models', 'output_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_models', 'input_cost',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.0'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'video_llm_model_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Specific LLM model for video analysis',
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'image_llm_model_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Specific LLM model for image analysis',
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'text_llm_model_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Specific LLM model for text analysis',
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'output_display_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Configuration for rich display in dashboard',
               existing_comment='Configuration for rich display in dashboard (sentiment emoji, keywords, links, etc.)',
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'response_format_config',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='Configuration for automatic JSON schema generation',
               existing_comment='Configuration for automatic JSON schema generation. Controls response structure.',
               existing_nullable=True,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'analysis_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               schema='social_manager')
    op.alter_column('bot_scenarios', 'content_types',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               schema='social_manager')
    op.drop_column('ai_analytics', 'main_topics', schema='social_manager')
    # ### end Alembic commands ###
