"""add analyze_type to bot_scenario

Revision ID: 0040
Revises: 0039
Create Date: 2025-10-31 19:34:54.181722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0040'
down_revision: Union[str, Sequence[str], None] = '0039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            CREATE TYPE social_manager.analyze_type AS ENUM (
                'themes',
                'days'
            )
        """)

    op.add_column('bot_scenarios', sa.Column('analyze_type', sa.Enum('themes', 'days', name='analyze_type', schema='social_manager', inherit_schema=True), nullable=True), schema='social_manager')
    op.drop_column('bot_scenarios', 'output_display_config', schema='social_manager')
    op.drop_column('bot_scenarios', 'response_format_config', schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_scenarios', sa.Column('response_format_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Configuration for automatic JSON schema generation. Controls response structure.'), schema='social_manager')
    op.add_column('bot_scenarios', sa.Column('output_display_config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Configuration for rich display in dashboard (sentiment emoji, keywords, links, etc.)'), schema='social_manager')
    op.drop_column('bot_scenarios', 'analyze_type', schema='social_manager')
    # ### end Alembic commands ###
