"""fix_defaults_and_nullables

Revision ID: 0046
Revises: 0045
Create Date: 2026-09-24 03:14:41.861199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0046'
down_revision: Union[str, Sequence[str], None] = '0045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_models', 'model_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_models', 'max_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_models', 'default_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_providers', 'api_format',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_providers', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True,
               schema='social_manager')
    op.alter_column('llm_providers', 'api_key_env',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               schema='social_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_providers', 'api_key_env',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               schema='social_manager')
    op.alter_column('llm_providers', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False,
               schema='social_manager')
    op.alter_column('llm_providers', 'api_format',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'openai'::character varying"),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_models', 'default_temperature',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text('0.3'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_models', 'max_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('4096'),
               existing_nullable=False,
               schema='social_manager')
    op.alter_column('llm_models', 'model_type',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'text'::character varying"),
               existing_nullable=False,
               schema='social_manager')
    # ### end Alembic commands ###
