"""add last_request_cost to llm_models

Revision ID: 0047
Revises: 0046
Create Date: 2026-09-24 23:30:56.476590

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0047"
down_revision: Union[str, Sequence[str], None] = "0046"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "llm_models",
        sa.Column(
            "last_request_cost", sa.Float(), nullable=True, comment="Estimated cost of the last test request (USD)"
        ),
        schema="social_manager",
    )
    op.add_column(
        "llm_models",
        sa.Column(
            "last_request_cost_at",
            sa.DateTime(),
            nullable=True,
            comment="When last infra cost was computed",
        ),
        schema="social_manager",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_models", "last_request_cost_at", schema="social_manager")
    op.drop_column("llm_models", "last_request_cost", schema="social_manager")
    # ### end Alembic commands ###
